### ISSUE TITLE
Gamemode crashes the server

### ISSUE THREAD

**Issue by Joaquel** [Batfoxkid/SCP-Secret-Fortress#15]
When switching from game mode to SCP: SF, the server crashes and prints the following log on the console:

`[DHOOKS] FATAL: Failed to find return address of original function. Check the arguments and return type of your detour setup.`

The server OS is Windows, so maybe there's a with the Gamedata i think.

**Comment by Batfoxkid** [comment]
I also run a Windows server and have no issues, make sure gamedata (and possibly DHooks) is up to date.

**Comment by Joaquel** [comment]
I'll try to see if drowngrading to FlaminSarge version fix this (actually using nosoop TF2Attributes Fork).

**Comment by Joaquel** [comment]
> I'll try to see if drowngrading to FlaminSarge version fix this (actually using nosoop TF2Attributes Fork).

Nothing, I tried again with that version and it keeps crashing.

**Comment by Joaquel** [comment]
Problem fixed by unloading scp_sf plugin in Server.cfg.
Many thanks!
