### ISSUE TITLE
Framedrop when playing scp

### ISSUE THREAD

**Issue by M60TM** [Batfoxkid/SCP-Secret-Fortress#36]
In two cases, a frame drop occurs, one of which occurs for no particular reason when playing with an SCP. In this case, non-SCP people have no frame drop at all. On the other hand, frame drops that cannot be seen in other game modes occur when all mtf or chaos shoot at one SCP. In the first case, frame drops sometimes do not occur, but they occur frequently.

**Comment by Batfoxkid** [comment]
Any specific map, SCPs, etc.?

**Comment by M60TM** [comment]
all the map, and It doesn't happen to specific SCP.

**Comment by justkamiii** [comment]
Can reproduce, I've experienced this multiple times while playing as SCP. I can record if needed once I finish some stuff

**Comment by Joaquel** [comment]
I talked to Batfoxkid about this issue in Steam, so the issue is related to one of the sounds used in all maps (can be elevator.wav maybe).
