### ISSUE TITLE
SCP sound bug

### ISSUE THREAD

**Issue by Firerr** [Batfoxkid/SCP-Secret-Fortress#7]
all sounds including vc seems to playing as crackly broken audio, this includes both you and other players movement, gun shots, melee sounds and voice chat.

**Comment by Batfoxkid** [comment]
Are you sure this is related to SCP and not a server specific plugin?

**Comment by Firerr** [comment]
I could not tell you, will need investigation but, this issue only occurs in the scp gamemode. so its an scp plugin or an plugin breaking in scp.

**Comment by Firerr** [comment]
quick update, I've found that if you have the scoreboard as an SCP open the audio/voice plays normally.

**Comment by Batfoxkid** [comment]
Going to close this for now. Let me know if you can figure out what causes this and/or videos of it happening.
